name: Ghost Engine Pulse

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Ghost Engine Script
        env:
          PRODUCT_URL: ${{ secrets.PRODUCT_URL }}
        run: python engine.py

      - name: Commit and push if it changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Ghost Engine: Auto-update" && git push
